access_by_lua_file /etc/nginx/lua/gateway/access.lua;
header_filter_by_lua_file /etc/nginx/lua/gateway/header_filter.lua;
body_filter_by_lua_file /etc/nginx/lua/gateway/body_filter.lua;
log_by_lua_file /etc/nginx/lua/gateway/log.lua;
