upstream frontend_backend {
    zone frontend_backend 64k;
    server frontend:80 resolve max_fails=3 fail_timeout=15s;
    keepalive 32;
}

upstream api_backend {
    zone api_backend 64k;
    least_conn;
    server api-service:80 resolve max_fails=3 fail_timeout=15s;
    keepalive 64;
}

upstream admin_backend {
    zone admin_backend 64k;
    server admin-service:80 resolve max_fails=3 fail_timeout=15s;
    keepalive 16;
}

upstream echo_backend {
    zone echo_backend 64k;
    server echo-service:8080 resolve max_fails=3 fail_timeout=15s;
    keepalive 64;
}
